# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent


# 鼠标绘画事件
class MyLabel(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super(MyLabel, self).__init__(parent)
        self.x0, self.y0 = 0, 0  # 鼠标按下的初始位置
        self.x1, self.y1 = 0, 0  # 鼠标当前位置
        self.flag = False  # 鼠标是否按下
        self.move = False  # 是否在移动状态

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.x0, self.y0 = event.pos().x(), event.pos().y()
            self.flag = True

    def mouseMoveEvent(self, event):
        if self.flag:
            self.move = True
            self.x1, self.y1 = event.pos().x(), event.pos().y()
            self.update()

    def mouseReleaseEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.flag = False
            self.move = False

    def paintEvent(self, event):
        super().paintEvent(event)
        if self.flag and self.move:
            painter = QtGui.QPainter(self)
            painter.setPen(QtGui.QPen(QtCore.Qt.red, 2, QtCore.Qt.SolidLine))
            painter.drawRect(QtCore.QRect(self.x0, self.y0, self.x1 - self.x0, self.y1 - self.y0))



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1618, 947)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icons/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1298, 848))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1300, 850))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(9, 9, 2000, 1000))
        self.label_3.setStyleSheet("background: gray;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.videoWidget = QVideoWidget(self.label_3)

        self.mediaPlayer = QMediaPlayer()
        self.mediaPlayer.setVideoOutput(self.videoWidget)
        
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 2000, 1000))
        self.label_4.setMouseTracking(True)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        # 如果 scrollAreaWidgetContents 没有布局，给它设置一个默认布局
        if not self.scrollAreaWidgetContents.layout():
            self.layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
            self.scrollAreaWidgetContents.setLayout(self.layout)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        MainWindow.setCentralWidget(self.centralwidget)
        self.setSplitterSizes()

        self.currentImageLabel = QtWidgets.QLabel(self.layoutWidget)
        self.currentImageLabel.setObjectName("currentImageLabel")
        self.currentImageLabel.setWordWrap(True)
        self.verticalLayout.addWidget(self.currentImageLabel)
        self.groupBox_videoControls = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_videoControls.setObjectName("groupBox_videoControls")
        self.verticalLayout_videoControls = QtWidgets.QVBoxLayout(self.groupBox_videoControls)
        self.verticalLayout_videoControls.setObjectName("verticalLayout_videoControls")
        self.verticalLayout_videoControls.setSpacing(8)
        self.verticalLayout_videoControls.setContentsMargins(12, 12, 12, 12)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_videoControls)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.progressBar.hide()
        self.verticalLayout_videoControls.addWidget(self.progressBar)
        self.slider_video = QtWidgets.QSlider(self.groupBox_videoControls)
        self.slider_video.setEnabled(False)
        self.slider_video.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video.setObjectName("slider_video")
        self.verticalLayout_videoControls.addWidget(self.slider_video)
        self.verticalLayout.addWidget(self.groupBox_videoControls)
        self.groupBox_videoMarking = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_videoMarking.setObjectName("groupBox_videoMarking")
        self.gridLayout_videoMarking = QtWidgets.QGridLayout(self.groupBox_videoMarking)
        self.gridLayout_videoMarking.setObjectName("gridLayout_videoMarking")
        self.gridLayout_videoMarking.setSpacing(8)
        self.gridLayout_videoMarking.setContentsMargins(12, 12, 12, 12)
        self.pushButton_play = QtWidgets.QPushButton(self.groupBox_videoMarking)
        self.pushButton_play.setEnabled(False)
        self.pushButton_play.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_play.setObjectName("pushButton_play")
        self.gridLayout_videoMarking.addWidget(self.pushButton_play, 0, 0, 1, 1)
        self.pushButton_pause = QtWidgets.QPushButton(self.groupBox_videoMarking)
        self.pushButton_pause.setEnabled(False)
        self.pushButton_pause.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.gridLayout_videoMarking.addWidget(self.pushButton_pause, 0, 1, 1, 1)
        self.pushButton_capture = QtWidgets.QPushButton(self.groupBox_videoMarking)
        self.pushButton_capture.setEnabled(False)
        self.pushButton_capture.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_capture.setObjectName("pushButton_capture")
        self.gridLayout_videoMarking.addWidget(self.pushButton_capture, 1, 0, 1, 1)
        self.pushButton_autoCapture = QtWidgets.QPushButton(self.groupBox_videoMarking)
        self.pushButton_autoCapture.setEnabled(False)
        self.pushButton_autoCapture.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_autoCapture.setObjectName("pushButton_autoCapture")
        self.gridLayout_videoMarking.addWidget(self.pushButton_autoCapture, 1, 1, 1, 1)
        self.pushButton_replay = QtWidgets.QPushButton(self.groupBox_videoMarking)
        self.pushButton_replay.setEnabled(False)
        self.pushButton_replay.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_replay.setObjectName("pushButton_replay")
        self.gridLayout_videoMarking.addWidget(self.pushButton_replay, 2, 0, 1, 1)
        self.pushButton_start_marking = QtWidgets.QPushButton(self.groupBox_videoMarking)
        self.pushButton_start_marking.setEnabled(False)
        self.pushButton_start_marking.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_start_marking.setObjectName("pushButton_start_marking")
        self.gridLayout_videoMarking.addWidget(self.pushButton_start_marking, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_videoMarking)
        self.groupBox_labelList = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_labelList.setObjectName("groupBox_labelList")
        self.verticalLayout_labelList = QtWidgets.QVBoxLayout(self.groupBox_labelList)
        self.verticalLayout_labelList.setObjectName("verticalLayout_labelList")
        self.verticalLayout_labelList.setSpacing(8)
        self.verticalLayout_labelList.setContentsMargins(12, 12, 12, 12)
        self.label_2 = QtWidgets.QLabel(self.groupBox_labelList)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_labelList.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_labelList)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalLayout_labelList.addWidget(self.listWidget)
        self.verticalLayout.addWidget(self.groupBox_labelList)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1618, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSaveType = QtWidgets.QMenu(self.menubar)
        self.menuSaveType.setObjectName("menuSaveType")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Dir.setIcon(icon1)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")

        self.actionOpen_Dir.triggered.connect(self.enableLabel4)

        self.actionChange_Save_Dir = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChange_Save_Dir.setIcon(icon2)
        self.actionChange_Save_Dir.setObjectName("actionChange_Save_Dir")
        self.actionNext_Image = QtWidgets.QAction(MainWindow)
        self.actionNext_Image.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI/icons/next.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_Image.setIcon(icon3)
        self.actionNext_Image.setObjectName("actionNext_Image")
        self.actionPrev_Image = QtWidgets.QAction(MainWindow)
        self.actionPrev_Image.setEnabled(False)
        self.actionVideo_marking = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("GUI/icons/Video_marking.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVideo_marking.setIcon(icon7)
        self.actionVideo_marking.setObjectName("actionVideo_marking")

        self.actionVideo_marking.triggered.connect(self.enableLabel4)

        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("GUI/icons/prev.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev_Image.setIcon(icon4)
        self.actionPrev_Image.setObjectName("actionPrev_Image")
        self.actionCreate_RectBox = QtWidgets.QAction(MainWindow)
        self.actionCreate_RectBox.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("GUI/icons/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_RectBox.setIcon(icon5)
        self.actionCreate_RectBox.setObjectName("actionCreate_RectBox")
        self.actionOpen_Video = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("GUI/icons/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Video.setIcon(icon6)
        self.actionOpen_Video.setObjectName("actionOpen_Video")



        self.actionOpen_Video.triggered.connect(self.disableLabel4)

        self.actionSaveTypeYOLO = QtWidgets.QAction(MainWindow)
        self.actionSaveTypeYOLO.setCheckable(True)
        self.actionSaveTypeYOLO.setObjectName("actionSaveTypeYOLO")
        self.actionSaveTypeXML = QtWidgets.QAction(MainWindow)
        self.actionSaveTypeXML.setCheckable(True)
        self.actionSaveTypeXML.setObjectName("actionSaveTypeXML")

        self.menuFile.addAction(self.actionOpen_Video)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addAction(self.actionChange_Save_Dir)
        self.menuFile.addAction(self.actionVideo_marking)
        self.menuFile.addAction(self.actionNext_Image)
        self.menuFile.addAction(self.actionPrev_Image)
        self.menuFile.addAction(self.actionCreate_RectBox)
        self.menuSaveType.addAction(self.actionSaveTypeYOLO)
        self.menuSaveType.addAction(self.actionSaveTypeXML)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSaveType.menuAction())


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setSplitterSizes(self):
        # 根据当前 splitter 的宽度设置比例
        total_size = self.splitter.size().width()
        size1 = int(0.8 * total_size)  # 第一个区域占75%
        size2 = total_size - size1  # 第二个区域占剩余的20%
        self.splitter.setSizes([size1, size2])

    def enableLabel4(self):
        # 点击打开目录后启用 MyLabel
        self.label_4.deleteLater()  # 删除原来的 QLabel
        
        # 创建 MyLabel 实例并添加到布局
        self.label_4 = MyLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 2000, 1000))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.scrollAreaWidgetContents.layout().addWidget(self.label_4)
        


    def disableLabel4(self):
        self.label_4.deleteLater()  # 删除原来的 QLabel
        
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 2000, 1000))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.scrollAreaWidgetContents.layout().addWidget(self.label_4)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Yolo Labeler"))
        self.currentImageLabel.setText(_translate("MainWindow", ""))
        self.groupBox_labelList.setTitle(_translate("MainWindow", "标签列表"))
        self.label_2.setText(_translate("MainWindow", "标签箱"))
        self.groupBox_videoControls.setTitle(_translate("MainWindow", "视频操作"))
        self.groupBox_videoMarking.setTitle(_translate("MainWindow", "视频打标"))
        self.pushButton_play.setText(_translate("MainWindow", "开始"))
        self.pushButton_pause.setText(_translate("MainWindow", "暂停"))
        self.pushButton_capture.setText(_translate("MainWindow", "抽帧"))
        self.pushButton_autoCapture.setText(_translate("MainWindow", "自动抽帧"))
        self.pushButton_replay.setText(_translate("MainWindow", "重新播放"))
        self.pushButton_start_marking.setText(_translate("MainWindow", "目标跟踪"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSaveType.setTitle(_translate("MainWindow", "Save Type"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "E"))
        self.actionChange_Save_Dir.setText(_translate("MainWindow", "Change Save Dir"))
        self.actionChange_Save_Dir.setShortcut(_translate("MainWindow", "R"))
        self.actionNext_Image.setText(_translate("MainWindow", "Next Image"))
        self.actionNext_Image.setShortcut(_translate("MainWindow", "D"))
        self.actionPrev_Image.setText(_translate("MainWindow", "Prev Image"))
        self.actionPrev_Image.setShortcut(_translate("MainWindow", "A"))
        self.actionCreate_RectBox.setText(_translate("MainWindow", "Create RectBox"))
        self.actionCreate_RectBox.setShortcut(_translate("MainWindow", "W"))
        self.actionOpen_Video.setText(_translate("MainWindow", "Open Video"))
        self.actionOpen_Video.setShortcut(_translate("MainWindow", "V"))
        self.actionVideo_marking.setText(_translate("MainWindow", "Video marking"))
        self.actionVideo_marking.setShortcut(_translate("MainWindow", "M"))
        self.actionSaveTypeYOLO.setText(_translate("MainWindow", "YOLO"))
        self.actionSaveTypeXML.setText(_translate("MainWindow", "XML"))

